### ISSUE TITLE
docs - unclear how many tweets will be synced upon first run

### ISSUE THREAD

**Issue by rzca** [louisgrasset/touitomamout#199]
I'm not sure from the documentation if running touitomamout for the first time will post every single one of my tweets to bluesky. If so, it would be good to make this configurable so that you can only sync new tweets.

**Comment by louisgrasset** [comment]
Touitomamout relies on the [200 entries ref](https://github.com/louisgrasset/touitomamout/blob/09318c1d48dbc31e135d61544b6afe1765d8bf40/src/services/tweets-getter.service.ts#L75) recent entries of your account (RT, Tweets, Answers...). 

It won't sync more than 200.

Some checks are performed on the 5 most recent entries so that if one is already cached, then there is no need to look for even older posts.

On these 200, keep in mind a filter is applied on a couple of criteria (the post is a RT, the post is an answer to someone else than you... etc)
